name: Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: npm ci && npm run alfredPackage
      - name: Upload workflow artifact
        uses: actions/upload-artifact@v1
        with:
          name: alfred_slack.alfredworkflow
          path: alfred_slack.alfredworkflow
